[package]
name = "db"
version = "0.1.0"
authors = ["LINE <769483043@qq.com>"]
edition = "2018"

[dependencies]
lmdb = "0.8.0"
log = "0.4.6"

crypto = {path = "../crypto"}
cryptonote_basic = {path = "../cryptonote_basic"}
