[package]
name = "cryptonote_core"
version = "0.1.0"
authors = ["LINEZH <huizhaoline@gmail.com>"]
edition = "2018"

[dependencies]
db = {path = "../db"}
crypto = {path = "../crypto"}
cryptonote_basic = {path = "../cryptonote_basic"}
checkpoints = {path = "../checkpoints"}

tokio = "0.1.13"
