[package]
name = "xmr_cryptonote_basic"
version = "0.1.0"
authors = ["LINE <769483043@qq.com>"]
edition = "2018"

[dependencies]
xmr_crypto = {path = "../crypto"}
xmr_device = {path = "../device"}
xmr_db = {path = "../db"}
