[package]
name = "cryptonote_basic"
version = "0.1.0"
authors = ["LINE <769483043@qq.com>"]
edition = "2018"

[dependencies]
crypto = {path = "../crypto"}
device = {path = "../device"}
#db = {path = "../db"}

tokio = "0.1.13"